### ISSUE TITLE
Output get confused when flow server is starting

### ISSUE THREAD

**Issue by chrisnojima** [ryyppy/flow-vim-quickfix#1]
Hey,

Thanks for making this! I noticed that if I was getting the flow starting messages it seems to confuse neomake. I updated the script to be 

```
          \ 'args': ['-c', g:flow_path.' --json 2>/dev/null| flow-vim-quickfix'],
```

which seems to fix it.

**Comment by ryyppy** [comment]
Ah, yeah, I was actually used to this behavior from the original vim-flow project... will add this later to the README after I tried this ... thanks :-)

**Comment by ryyppy** [comment]
Tried it and it looks better now! Updated the README ... thanks again :+1:
