### ISSUE TITLE
Doesn't work when opening a buffer

### ISSUE THREAD

**Issue by simonsmith** [ryyppy/flow-vim-quickfix#2]
Hey,

Using the config from the README it doesn't work unless I type `:Neomake flow` as a command. I've provided a clip of me opening a buffer with `eslint` and `flow` enabled to demonstrate:

https://cl.ly/hJ9i

Any ideas?
Thanks

**Comment by ryyppy** [comment]
What is your neomake configuration? 
I never consciously thought about it, but I usually open my files and enter `:w` first, after that my neomake runs `flow` ... I guess it is possible to configure neomake for an "on-file-open" event?

**Comment by simonsmith** [comment]
I have this:

```
if s:has_plugin('neomake')
  let g:neomake_list_height = 6

  if has('autocmd')
    autocmd! BufWritePost,BufRead * Neomake
    autocmd! QuitPre * let g:neomake_verbose = 0
  endif
endif
```

I also have the code snippet from the README.

Other makers that I use run on `BufRead` as you saw with the video. `flow` doesn't seem to run for me even when I write the buffer. If I remove `eslint` so that `flow` is the only maker it still doesn't run.

**Comment by simonsmith** [comment]
With further testing I have the same issue when using just the default Flow from Neomake. The problem must be there. Sorry!

**Comment by ryyppy** [comment]
Hmm, no worries, the problem has to be `neomake` since my program doesn't do any essential things but formatting the --json output...

I tried your config and in my case it works... 
My NeoVim version: `NVIM 0.1.4`

**Comment by simonsmith** [comment]
I see. I'm running 0.1.5, wonder if that's related. Thanks
